version: "3"

services:

  geolocations_api:
# Uncomment if you are on Linux
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    image: "bandnoticeboard/geolocations-api:latest"
    ports:
      - "7000:7000"
    environment:
      API_DB_NAME: towns_db
      API_DB_USERNAME: admin
      API_DB_PASSWORD: admin
      API_DB_HOST: host.docker.internal
      API_DB_PORT: 27017
      SERVER_PORT: 6000
      SERVER_HOST: 0.0.0.0

  postgres_etl:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: location_etl_db
    volumes:
      - ./db-data_local/postgres_db_volume/:/var/lib/postgresql/data/

volumes:
  postgres_db: