services:
  postgres_etl:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: location_etl_db
    volumes:
      - ./db-data_local/postgres_db_volume/:/var/lib/postgresql/data/

  postgres_test:
    image: "postgres:latest"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: location_etl_test_db
    volumes:
      - ./db-data_test/postgres_db_volume/:/var/lib/postgresql/data/


volumes:
  postgres_db:
  postgres_test:
