version: "3"

services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: locations_db

    volumes:
      - ./db-data_local/postgres_db_volume/:/var/lib/postgresql/data/


volumes:
    postgres_db: