version: "3"

services:

  geolocations_api:
# Uncomment if you are on Linux
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    image: "bandnoticeboard/geolocations-api:latest"
    ports:
      - "8000:8000"
    environment:
      PGPORT: 5433
      PGDATABASE: location_etl_db
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: host.docker.internal
      SERVER_PORT: 8000
      SERVER_HOST: 0.0.0.0

  postgres_etl:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: location_etl_db
    volumes:
      - ./db-data_local/postgres_db_volume/:/var/lib/postgresql/data/

volumes:
  postgres_db: