name: Makefile CI

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: make docker-build ${{ steps.release.outputs.version }}
      
    - name: Install dependencies
      run: make docker-push ${{ secrets.DOCKER_USERNAME }}, ${{ secrets.DOCKER_PASSWORD }}, {{ secrets.DOCKER_EMAIL }}
      

